WITH RANKED_ECOLI AS (
    SELECT ID, SIZE_OF_COLONY,
           PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
    FROM ECOLI_DATA
)
SELECT ID, 
       CASE 
           WHEN PCT <= 0.25 THEN 'CRITICAL'
           WHEN PCT <= 0.50 THEN 'HIGH'
           WHEN PCT <= 0.75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM RANKED_ECOLI
ORDER BY ID;
