WITH RECURSIVE GENERATION_DATA AS (
    -- 1️⃣ [기본 쿼리] 1세대 찾기 (부모가 없는 개체)
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 2️⃣ [재귀 쿼리] 이전 세대(GENERATION_DATA)의 ID를 PARENT_ID로 가지는 개체 찾기
    SELECT e.ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATION_DATA g ON e.PARENT_ID = g.ID
)
-- 3️⃣ [출력] 세대별 자식이 없는 개체 수 집계
SELECT COUNT(g.ID) AS COUNT, g.GENERATION
FROM GENERATION_DATA g
LEFT JOIN ECOLI_DATA e ON g.ID = e.PARENT_ID  -- 자식이 없는 개체 찾기
WHERE e.PARENT_ID IS NULL  -- 자식이 없는 개체만 선택
GROUP BY g.GENERATION
ORDER BY g.GENERATION;
