WITH a AS (SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
FROM FIRST_HALF

UNION ALL

SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
FROM JULY)

SELECT FLAVOR
FROM a
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;