SELECT
    I.ID,
    N.FISH_NAME,
    I.LENGTH
FROM
    FISH_INFO AS I
JOIN
    FISH_NAME_INFO AS N
ON
    I.FISH_TYPE = N.FISH_TYPE
WHERE
    I.LENGTH = (
        SELECT MAX(LENGTH)
        FROM FISH_INFO AS FI
        WHERE FI.FISH_TYPE = I.FISH_TYPE
    );