SELECT SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
JOIN 
    (SELECT SUM(SCORE) AS SCORE, EMP_NO
     FROM HR_GRADE
     GROUP BY EMP_NO) g
ON e.EMP_NO = g.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
